[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rcraft_viz"
version = "0.0.1"
description = "RTS-style autonomous unit simulator GUI"
authors = [
  { name = "Edwin Reidlo" }
]
dependencies = [
  "PyQt5",
  "Pillow<=10",
  "pyyaml",
  "opencv-python",
  "numpy",
  "rcraft_cython"
]
requires-python = ">=3.7"

[project.scripts]
rcraft-gui = "rcraft_viz.main:main"
